const Config = require('./config');
const fs = require('fs');
const chalk = require("chalk")

if (fs.existsSync("./language/" + Config.LANG + ".json")) {
  console.log(chalk.green.bold("Loading " + Config.LANG + " language..."))

  var json = JSON.parse(
    fs.readFileSync("./language/" + Config.LANG + ".json")
  )
} else {
  console.log(
    chalk.red.bold("اللغة المطلوبة مش موجودة، هستخدم العربي بدلها 🫠")
  )

  var json = JSON.parse(fs.readFileSync("./language/EN.json"))
}

// الردود الأساسية باللهجة المصرية. أسماء المفاتيح ثابتة حتى تفضل كل الإضافات
// القديمة شغالة، ومن غير ما نعمل ملف لغة جديد ملوش لازمة.
const ARABIC = {
  _asena: {
    DESC:
      "إدارة البوت والدردشة.\n.lydia في الشات تفعّل ليديا للجروب كله.\n" +
      "رد على شخص أو اعمله منشن عشان تفعّلها له 👽",
    L_ACTIVATED: "```ليديا اشتغلت لـ {}\nولإيقافها اكتب .lydia stop```",
    L_DEACTIVATED: "```ليديا وقفت لـ {}```",
    L_NOT_ACTIVATED: "```ليديا مش شغالة لـ {}```",
  },
  _plugin: {
    INSTALL_DESC: "تثبيت إضافة خارجية.",
    NEED_URL: "```ابعت رابط يا نجم!\nمثال: .plugin الرابط```",
    INVALID_URL: "```الرابط ده مش مظبوط 😾```",
    INVALID_PLUGIN: "*❌ الإضافة دي مش صالحة يا معلم!*\n*الخطأ:*",
    INSTALLED: "*✅ الإضافة {} اتثبتت بنجاح 🔥*",
    PLUGIN_DESC: "عرض الإضافات المثبتة.",
    INSTALLED_FROM_REMOTE: "✅*الإضافات اللي اتثبتت من برّه:*\n",
    NO_PLUGIN: "*مفيش إضافات خارجية متثبتة هنا 🫠*",
    REMOVE_DESC: "حذف إضافة.",
    NEED_PLUGIN: "```اكتب اسم الإضافة يا باشا! مثال: .plugin utl```",
    NOT_FOUND_PLUGIN: "```مش لاقي إضافة بالاسم ده 🤡```",
    DELETED: "*✅ الإضافة اتحذفت. اعمل ريستارت عشان التغيير يشتغل 🔥*",
  },
  admin: {
    BAN_DESC: "اطرد حد من الجروب بالرد على رسالته أو بعمل منشن.",
    IM_NOT_ADMIN: "*أنا مش أدمن في الجروب ده 😾*",
    REMOVE_ALL: "```بنشيل الناس كلها... محدش يزعل بقى 🤡```",
    IS_ADMIN: "*ده أدمن يا معلم، مش هينفع يتطرد 😼*",
    BANNED: "```@{} خرج من الجروب بالسلامة 🫠```",
    FAILED: "```مش عرفت أضيفه، بعتله دعوة بدل كده```!",
    GIVE_ME_USER: "*حدد شخص بالرد أو المنشن يا نجم!*",
    ADD_DESC: "إضافة شخص للجروب.\n.add 201005560325",
    ADDED: "```@{} اتضاف للجروب 🔥```",
    ALREADY_PROMOTED: "```هو أدمن أصلًا، أرقّيه إيه تاني؟ 😼```",
    PROMOTED: "```@{} بقى أدمن 🔥```",
    PROMOTE_DESC: "ترقية شخص لأدمن بالرد أو المنشن.",
    DEMOTE_DESC: "سحب صلاحيات الأدمن بالرد أو المنشن.",
    ALREADY_NOT_ADMIN: "```ده مش أدمن أصلًا يا معلم```",
    DEMOTED: "```@{} صلاحياته اتسحبت 😾```",
    MUTE_DESC:
      "كتم الجروب.\n.mute للكتم الدائم\n.mute 10 للكتم 10 دقايق",
    MUTED: "```الجروب اتكتم 🤫```",
    TMUTE: "```الجروب اتكتم لمدة ",
    UNMUTE_DESC: "فتح الكتم عن الجروب.\n.unmute",
    UNMUTED: "```الجروب رجع يتكلم تاني 😼```",
    INVITE_DESC: "هات لينك دعوة الجروب.",
    COMMON_DESC: "عرض الأعضاء المشتركين بين جروبين.",
    SYNTAX: "*الصيغة مش مظبوطة يا نجم 😾*",
    INVALID_JID: "*معنديش صلاحية أوصل للجروبات دي 🫠*",
    DIFF_DESC: "عرض الأعضاء المختلفين بين جروبين.",
    JOIN_DESC: "انضم لجروب من لينك الدعوة.",
    JOIN_ERR: "*ده مش لينك دعوة واتساب صالح 🤡*",
    JOINED: "```دخلت الجروب 🔥```",
    REVOKE_DESC: "إلغاء لينك دعوة الجروب.",
    REVOKE: "```اللينك القديم اتلغى بنجاح```",
  },
  docx: {
    TOPDF_DESC: "تحويل ملف لـ PDF بالرد على ملف زي PPT أو DOCX.",
    REPLY: "*رد على صورة الأول*",
    REPLY_MSG: "رد على رسالة يا نجم",
    NOT_SUPPORTED: "*الرسالة دي مش قابلة للتحويل لـ PDF 😾*",
    WASTED_DESC: "عمل بانر Wasted بالرد على صورة.",
    TRIGGERED_DESC: "عمل بانر Triggered بالرد على صورة.",
    READMORE_DESC: "إضافة زر اقرأ المزيد للرسالة.",
    BROADCAST_DESC: "إرسال أو إعداد بث جماعي.",
    BROADCAST_EXAMPLE: "مثال:\n.broadcast 'صحاب' 'jid1 jid2 jid3'",
    BROADCAST_SET: "```اتضاف {} للبث.\nدلوقتي رد على رسالة واكتب .broadcast {}```",
    BROADCASTING: "```ببعت لـ\n {}```",
  },
  groupmute: {
    NO_SCHEDULE: "*مفيش مواعيد محفوظة نعرضها 🫠*",
    SYNTAX: "*الصيغة غلط يا باشا 😾*",
    NOT_FOUND: "*مش لاقي الموعد ده*",
    NEED_REPLY: "*رد على رسالة نصية الأول*",
    GJID: "*هات معرّف الجروب يا معلم*",
    MUTE: "```هكتم {} الساعة {}:{}```\n\n*اعمل ريستارت عشان يشتغل.*",
    UNMUTE: "```هفتح كتم {} الساعة {}:{}```\n\n*اعمل ريستارت عشان يشتغل.*",
  },
  insta: {
    INSTA_DESC: "تنزيل منشور أو ريلز أو IGTV من إنستجرام.",
    NEED_REPLY: "*هات رابط يا نجم.*",
    DOWNLOADING: "```بنزل...```",
    STORY_DESC: "تنزيل ستوريز يوزر معين.",
    DOWNLOADING_STORY: "```بنزل ستوريز {}...```",
    NOT_FOUND: "*مش لاقي حاجة!*",
    SIZE: "*الفيديو حجمه {}MB ومش قادر أرفعه.*\n*SD:* {}\n*HD:* {}",
    CAPTION: "*رابط HD:* {}",
    FB_DESC: "تنزيل فيديو من فيسبوك.",
  },
  media: {
    ROTATE_DESC: "لف فيديو مردود عليه. استخدم right أو left أو flip.",
    CHOOSE: "*اختار right أو left أو flip.*",
    WRONG: "*الاختيار غلط يا معلم*",
    NEED_REPLY: "*رد على فيديو!*",
    MP3_NEED_REPLY: "*رد على فيديو أو صوت!*",
    INEED_REPLY: "*رد على صورة!*",
    NEED_CUT_REPLY: "*رد على صوت!*",
    DOWNLOADING: "```بنزل الفيديو وبعدله...```",
    AUDIO_DOWNLOADING: "```بنزل الصوت وبعدله...```",
    CF: "```التنزيل فشل 😾```",
    MP3_DESC: "تحويل فيديو مردود عليه لـ MP3.",
    PHOTO_DESC: "تحويل ملصق صورة لصورة.",
    SNEED: "*رد على ملصق صورة.*",
    DOWNS: "```بنزل وبعدل الملصق...```",
    EMOJI: "تحويل إيموجي لصورة.",
    ENEED: "```هات إيموجي يا نجم.```",
    NEED_SAAVN: "```هات رابط يا معلم.```",
    SAAVN_DESC: "تنزيل أغنية من Jio Saavn.",
    NEED_SPOTIFY: "```هات رابط يا نجم.```",
    SPOTIFY_DESC: "تنزيل أغنية من Spotify.",
    UPLOAD: "تنزيل من رابط مباشر.",
    TRIM_DESC: "قص جزء من فيديو مردود عليه.",
    CUT_DESC: "قص جزء من صوت مردود عليه.",
    CUT_NEED_REPLY: "*اكتب وقت البداية;المدة.*\n*مثال: .cut 103;30*",
    TRIM_NEED_REPLY: "*اكتب وقت البداية;المدة.*\n*مثال: .trim 89;30*",
    REVERSE_DESC: "عكس فيديو أو صوت.",
    RE_NEED_REPLY: "*رد على صوت أو فيديو!*",
    SYNTAX: "*الصيغة غلط يا نجم!*",
    PDF_DESC: "طباعة الصفحات المضافة في PDF.",
    PAGE_DEC: "إضافة صفحات لتحويلها لـ PDF.",
    COMPRESS_DESC: "تقليل حجم الفيديو المردود عليه.",
    UNVOICE_DESC: "تحويل رسالة صوتية لصوت عادي.",
    VOICE_DESC: "تحويل صوت عادي لرسالة صوتية.",
    LOW_DESC: "تعديل طبقة الصوت لتحت.",
    PITCH_DESC: "تعديل طبقة الصوت.",
    AVEC_DESC: "تحويل صوت مردود عليه لفيديو.",
  },
  greetings: {
    WELCOME_DESC: "تظبيط رسالة الترحيب. لو سبتها فاضية هعرض رسالة الترحيب.",
    NOT_SET_WELCOME: "*لسه مفيش رسالة ترحيب متظبطة 🫠*",
    WELCOME_ALREADY_SETTED: "*✅ رسالة الترحيب موجودة:*\n*الرسالة:* ```",
    NEED_WELCOME_TEXT: "*اكتب رسالة الترحيب يا نجم.*\n*مثال:* ```.welcome أهلا```",
    WELCOME_DELETED: "*✅ رسالة الترحيب اتمسحت.*",
    WELCOME_SETTED: "*✅ رسالة الترحيب اتظبطت 🔥*",
    GOODBYE_DESC: "تظبيط رسالة الوداع.",
    NOT_SET_GOODBYE: "*مفيش رسالة وداع متظبطة 🫠*",
    GOODBYE_ALREADY_SETTED: "*✅ رسالة الوداع موجودة:*\n*الرسالة:* ```",
    NEED_GOODBYE_TEXT: "*اكتب رسالة الوداع يا معلم.*",
    GOODBYE_DELETED: "*✅ رسالة الوداع اتمسحت.*",
    GOODBYE_SETTED: "*✅ رسالة الوداع اتظبطت.*",
    ON_OFF: "تشغيل أو إيقاف رسالة {}",
    W_ENABLED: "*✅ رسالة الترحيب {}*",
    G_ENABLED: "*✅ رسالة الوداع {}*",
    B_ENABLED: "*✅ رسالة البانباي {}*",
    ENABLE: "اشتغلت.",
    DISABLE: "وقفت.",
    BANBYE_DESC: "تظبيط رسالة طرد عضو.",
    NOT_SET_BANBYE: "*مفيش رسالة بانباي متظبطة 🫠*",
    NEED_BANBYE_TEXT: "*اكتب رسالة البانباي يا نجم.*",
    BANBYE_DELETED: "*✅ رسالة البانباي اتمسحت.*",
    BANBYE_SETTED: "*✅ رسالة البانباي اتظبطت.*",
    ANTIlink_DESC: "تشغيل أو إيقاف منع الروابط.",
    ANTILINK_DESC: "تشغيل أو إيقاف منع الروابط.\nمثال: .antilink on",
    NOT_ENABLED: "*{} مش شغال*",
    A_ON_OFF: "تشغيل أو إيقاف {}",
    A_ENABLED: "*✅ {} {}*",
    A_UPDATED: "```{} اتحدث```",
    ANTIFAKE_DESC: "تشغيل منع الأرقام الوهمية.",
    ANTIBAD_DESC: "تشغيل منع الكلمات الوحشة.",
    MENTION_DESC: "الرد على أي منشن.",
    M_ENABLE: "تشغيل أو إيقاف الرد على المنشن.",
  },
  afk: {
    AFK_DESC: "يخليك أوفلاين مؤقتًا — بعيد عن الكيبورد.",
    IM_AFK: "*أنا أوفلاين دلوقتي يا جماعة 🫠*",
    IM_AFK_NOMD: "أنا أوفلاين دلوقتي!",
    REASON: "السبب",
    LAST_SEEN: "آخر ظهور",
    IM_NOT_AFK: "```رجعت يا معلم 😼```",
    AFK_TEXT: "```بيب بوب! ده بوت، صاحبه مش موجود دلوقتي 👽```",
    AFK_TEXT_NOMD: "بيب بوب! ده بوت.",
    HOUR: "ساعة",
    MINUTE: "دقيقة",
    SECOND: "ثانية",
  },
  filters: {
    FILTER_DESC: "إضافة رد تلقائي. اكتب .filter لو عايز تشوف الفلاتر.",
    NO_FILTER: "*مفيش فلاتر في الشات ده 🫠*",
    FILTERS: "*الفلاتر الموجودة هنا 🔎:*",
    NEED_REPLY: "*اكتب الكلمة في رد يا نجم!*",
    FILTERED: "*✅ اتظبط الرد على* ```{}```",
    STOP_DESC: "إيقاف فلتر قديم.",
    NEED_FILTER: "*اكتب اسم الفلتر يا معلم!*",
    ALREADY_NO_FILTER: "*الفلتر ده مش موجود أصلًا 😾*",
    DELETED: "*✅ الفلتر اتمسح.*",
  },
  memes: {
    MEMES_DESC: "اعمل ميم من صورة مردود عليها.\n.meme فوق;تحت",
    NEED_REPLY: "*رد على صورة الأول يا نجم!*",
    DOWNLOADING: "```بنزل الصورة وبجهز الإفيه... 🗿```",
  },
  ocr: {
    OCR_DESC: "قراءة الكلام اللي في الصورة.",
    NEED_REPLY: "*رد على صورة يا معلم!*",
    DOWNLOADING: "```بنزل الصورة وبقرأها...```",
    ERROR: "```مش عرفت أقرأ الصورة :/```\n*الخطأ:*```{}```",
    RESULT: "*اللغة:* ```{}```\n*اللي قريته:* ```{}```",
    EDITOR: "قائمة تعديل الصور.",
  },
  profile: {
    KICKME_DESC: "اطردني من الجروب اللي بتستخدم فيه الأمر.",
    KICKME: "```سلام يا رجالة، أنا ماشي 🤠```",
    PP_DESC: "غيّر صورتي للصورة اللي مردود عليها.",
    NEED_PHOTO: "*هات صورة يا نجم!*",
    PPING: "```بظبط صورة البروفايل...```",
    BLOCK_DESC: "حظر شخص.",
    UNBLOCK_DESC: "فك حظر شخص.",
    BLOCKED: "اتحظر",
    UNBLOCKED: "اتفتح حظره",
    BLOCKED_UPPER: "اتحظر!",
    UNBLOCKED_UPPER: "الحظر اتمسح.",
    NEED_USER: "حدد شخص يا معلم!",
    JID_DESC: "عرض معرّف الشخص.",
    JID: "```معرّف @{} هو: {}```",
    JID_CHAT: "```معرّف الشات: {}```",
  },
  removebg: {
    REMOVEBG_DESC: "إزالة خلفية الصورة.",
    NEED_PHOTO: "*رد على صورة يا نجم!*",
    NO_API_KEY: "*حط مفتاح remove.bg في الإعدادات*",
    RBGING: "*المفتاح غلط 😾*",
    LIMIT: "*خلصت الحصة المجانية، استنى شوية أو حط مفتاح جديد.*",
  },
  nekobin: {
    NEKO_DESC: "حفظ الرسالة المردود عليها على nekobin.com.",
    NEED_REPLY: "```رد على رسالة يا نجم!```",
    MUST_TEXT: "```رد على أي رسالة نصية```",
  },
  heroku: {
    RESTART_DESC: "إعادة تشغيل البوت.",
    RESTART_MSG: "```البوت بيعمل ريستارت...```",
    SHUTDOWN_DESC: "إيقاف البوت.",
    SHUTDOWN_MSG: "```البوت بيقفل ⛔```",
    DYNO_DESC: "عرض استهلاك Heroku.",
    DYNO_TOTAL: "```الإجمالي```",
    DYNO_USED: "```المستخدم```",
    PERCENTAGE: "```النسبة```",
    DYNO_LEFT: "```المتبقي```",
    SETVAR_DESC: "تعديل متغير في Heroku.",
    SET_SUCCESS: "تم ضبط ```{} ➜ {}```",
    KEY_VAL_MISSING: "```المفتاح أو القيمة ناقصة```",
    INVALID: "```الصيغة لازم تكون key:value```",
    GETVAR_DESC: "عرض متغير من Heroku.",
    DELVAR_DESC: "حذف متغير من Heroku.",
    DEL_SUCCESS: "```{} اتمسح بنجاح```",
    NOT_FOUND: "```مش لاقي نتائج للمفتاح ده```",
    ERROR: "*راجع اسم تطبيق Heroku ومفتاح الـ API*",
    ALL_VARS: "عرض كل المتغيرات في إعدادات Heroku.",
  },
  evaluators: {
    TERM_DESC: "تشغيل أمر على الطرفية. استخدمه بحذر.",
    GIVE_ME_CODE: "*هات الكود يا معلم!*",
  },
  scrapers: {
    TRT: "اتترجم من {} لـ {}\n\n{}",
    TRANSLATE_DESC: "ترجمة أي رسالة.",
    TRANSLATE_USAGE: ".trt tr it (من التركي للإيطالي)",
    NEED_REPLY: "```رد على رسالة يا نجم!```",
    LANG: "اللغة",
    FROM: "اللغة المترجم منها",
    RESULT: "الترجمة",
    TRANSLATE_ERROR: "❌ حصلت مشكلة وأنا بترجم 😾",
    CURRENCY_ERROR: "```الصيغة غلط! مثال: .currency 1 TRY USD```",
    INVALID_CURRENCY: "```العملة اللي كتبتها مش مظبوطة```",
    UNKNOWN_ERROR: "```حصل خطأ، تحويل العملة فشل```",
    TTS_DESC: "تحويل الكلام لصوت.",
    TTS_ERROR: "```مش عرفت أعمل صوت للجملة دي```",
    SONG_DESC: "البحث عن أغنية وتنزيلها.",
    NEED_TEXT_SONG: "*اكتب اسم الأغنية يا نجم!*\n*مثال:* ```.song eminem rap god```",
    NO_RESULT: "*مش لاقي حاجة :(*",
    NO_SONG: "*الأغنية أطول من 10 دقايق.*",
    NO_VIDEO: "*الفيديو أطول من 15 دقيقة.*",
    SNO_VIDEO: "*الفيديو أطول من 7 دقايق.*",
    DOWNLOADING_SONG: "```بنزل الأغنية...```",
    UPLOADING_SONG: "```برفعها...```",
    VIDEO_DESC: "تنزيل فيديو من يوتيوب.",
    NEED_VIDEO: "*اكتب رابط فيديو يا معلم!*",
    DOWNLOADING_VIDEO: "```بنزل الفيديو...```",
    UPLOADING_VIDEO: "```برفع الفيديو...```",
    YT_DESC: "البحث على يوتيوب.",
    NEED_WORDS: "```اكتب كلمتين أدوّر بيهم يا نجم```",
    GETTING_VIDEOS: "```بجيبلك فيديوهات...```",
    NOT_FOUND: "*مش لاقي حاجة :(*",
    SEARCHING: "*🔎 بدوّر...*",
    WIKI_DESC: "البحث في ويكيبيديا.",
    IMG_DESC: "البحث عن صور مشابهة على جوجل.",
    IMG: "برفع الصورة ```{}``` رقم ```{}```...",
  },
  sticker: {
    STICKER_DESC: "حوّل صورة أو فيديو لملصق.",
    NEED_REPLY: "*رد على صورة أو فيديو يا معلم!*",
    MP4_NEED_REPLY: "*رد على ملصق متحرك.*",
    TAKE_DESC: "تغيير اسم وحساب حزمة الملصقات.",
    TAKE_NEED_REPLY: "*رد على ملصق الأول*",
    MP4_DESC: "حوّل الملصق المتحرك لفيديو.",
  },
  system_stats: {
    ALIVE_DESC: "تأكد إن البوت شغال.",
    SYSD_DESC: "عرض معلومات النظام.",
    WARN_DESC: "تحذير شخص بالرد أو المنشن.",
    NEED_USER: "*حدد شخص يا نجم*",
    IAADMIN: "*أنا مش أدمن*",
    ISADMIN: "*الشخص ده أدمن أصلًا*",
    WARNING: "```⚠️ تحذير ⚠️\nالشخص: @{}\nالسبب: {}\nالمتبقي: {}```",
    RESET: "```تم تصفير التحذيرات\nالشخص: @{}\nالمتبقي: {}```",
  },
  tagall: {
    TAGALL_DESC: "منشن لكل أعضاء الجروب.",
    VOTE_DESC: "عمل تصويت في الجروب.",
  },
  update: {
    UPDATER_DESC: "فحص تحديثات البوت.",
    UPDATE: "*البوت آخر حلاوة ومحدث 🔥*",
    NEW_UPDATE: "*في تحديث جديد للبوت!*\n\nالتغييرات:\n```",
    UPDATE_NOW_DESC: "تحديث البوت.",
    UPDATING: "_بحدث البوت..._",
    INVALID_HEROKU: "*❌ بيانات Heroku غلط!*",
    UPDATED: "*✅ اتحدث بنجاح!*",
    UPDATED_LOCAL: "*✅ اتحدث!*\n_اعمل ريستارت عشان التغييرات تشتغل._",
  },
  tiktok: {
    TIKTOK_DESC: "تنزيل فيديو تيك توك.",
    MOVIE_DESC: "عرض معلومات فيلم.\n.movie اسم الفيلم",
    INVALID: "*الرابط ده غلط يا نجم!*",
    NEED_NAME: "*اكتب اسم يا معلم*",
    NOT_FOUND: "*مش لاقي حاجة 🫠*",
    FORWARD: "*رد على رسالة الأول.*",
    FORWARD_DESC: "إعادة توجيه رسالة.",
    JID: "*هات معرّف الشات!*",
    WALLPAPER_DESC: "تنزيل خلفيات.",
    URL_DESC: "تحويل صورة أو فيديو لرابط.",
    URL_NEED_REPLY: "*رد على صورة أو فيديو!*",
  },
  twitter: {
    TWITTER_DESC: "تنزيل فيديو من تويتر.",
    PINTEREST_DESC: "تنزيل صورة أو فيديو من بنترست.",
    MEDIAFIRE_DESC: "تنزيل من ميديافاير.",
    SIZE: "مش قادر أنزّل، الحجم {}",
    NEED_REPLY: "*هات رابط يا نجم.*",
    NOT_FOUND: "*مش لاقي حاجة!*",
  },
  updown: {
    ATTP_DESC: "تحويل الكلام لملصق متحرك.",
    ATTP_NEED_REPLY: "*اكتب شوية كلام يا معلم.*",
    NOT_FOUND: "*مش لاقي حاجة!*",
    FIND_NEED_REPLY: "*رد على فيديو أو صوت.*",
    FIND_DESC: "معرفة الأغنية من فيديو أو صوت.",
    SS_DESC: "لقطة شاشة لموقع.",
    NEED_URL: "هات رابط يا نجم.",
    EMOJI_DESC: "تحويل إيموجي لملصق.",
    NEED_EMOJI: "*هات إيموجي يا معلم*",
    DOWNLOADING: "```بنزل...```",
    UPLOAD_DESC: "تنزيل من رابط مباشر.",
    SCL_DESC: "تنزيل أغنية من ساوند كلاود.",
  },
  weather: {
    WEATHER_DESC: "عرض حالة الطقس.\n.weather القاهرة",
    NEED_LOCATION: "*اكتب اسم المكان يا نجم!*\n*مثال:* ```.weather القاهرة```",
    COUNTRY: "الدولة",
    LOCATION: "المكان",
    FTEMP: "الإحساس",
    TEMP: "الحرارة",
    MAWIND: "أقصى حرارة",
    VISI: "الرؤية",
    SRISE: "الشروق",
    SET: "الغروب",
    DESC: "الوصف",
    HUMI: "الرطوبة",
    WIND: "سرعة الرياح",
    CLOUD: "السحاب",
    UPDATE: "آخر تحديث",
    NOT_FOUND: "```مش لاقي مدينة بالاسم ده 🫠```",
    YTV_DESC: "تنزيل فيديو يوتيوب.",
    YTV_NEED_REPLY: "*رد على رابط يوتيوب.*",
    DOWNLOADING: "```بنزل الفيديو...```",
    SIZE: "حجم الفيديو {}، مش قادر أرفعه.*",
    GOOGLE_DESC: "بحث عكسي بالصورة على جوجل.",
    INEED_REPLY: "*رد على صورة!*",
    INOT_FOUND: "*مش لاقي حاجة!*",
  },
  web: {
    SPEEDTEST_DESC: "قياس سرعة التحميل والرفع.",
    SPEEDTESTING: "```بجس السرعة...```",
    SPEEDTEST_RESULT: "*اختبار السرعة خلص يا معلم!*",
    UPLOAD: "رفع",
    DOWNLOAD: "تحميل",
    PING_DESC: "قياس سرعة استجابة البوت.",
  },
  vote: {
    voted: "```صوّت```",
    avoted: "```إنت صوّت قبل كده```",
    total: "إجمالي الأصوات: ",
    delete: "*التصويت اتمسح*",
    new: "*امسح التصويت الحالي واعمل واحد جديد.*",
    error: "*مش لاقي تصويت.*",
    syntax: "*الصيغة غلط*\nاكتب .help يا نجم",
  },
}

for (const [section, values] of Object.entries(ARABIC)) {
  if (json.STRINGS[section]) Object.assign(json.STRINGS[section], values)
}

function getString(file) {
  return json.STRINGS[file]
}

module.exports = {
  language: json,
  getString,
}